# Generated by Django 5.2.1 on 2025-06-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.JSONField()),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('inside_color', models.CharField()),
                ('border_color', models.CharField()),
            ],
        ),
    ]
