# Generated by Django 5.2.1 on 2025-06-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.JSONField(default=dict)),
                ('polygon', models.JSONField(default=dict)),
                ('inside_color', models.CharField()),
                ('border_color', models.CharField()),
            ],
        ),
    ]
