# Generated by Django 5.2.1 on 2025-06-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areapolygon',
            name='center',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='areapolygon',
            name='polygon',
            field=models.JSONField(),
        ),
    ]
