# Generated by Django 5.2.1 on 2025-07-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='category_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='category_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
