# Generated by Django 5.2.1 on 2025-07-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_groceryitem_category_image_groceryitem_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='category_tag',
            field=models.JSONField(default=list),
        ),
    ]
