# Generated by Django 5.2.1 on 2025-05-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(default='sent', max_length=200),
        ),
    ]
