# Generated by Django 5.2.1 on 2025-05-22 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_alter_suggestion_status'),
        ('user', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='user.customuser'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
