# Generated by Django 5.2.1 on 2025-08-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_alter_suggestion_subject_alter_suggestion_suggesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='subject',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggesion',
            field=models.CharField(blank=True),
        ),
    ]
