# Generated by Django 5.2.1 on 2025-05-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('offers', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('not_available', 'Not Available')], default='active', max_length=20)),
            ],
        ),
    ]
