# Generated by Django 5.2.1 on 2025-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_service_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='className',
            field=models.JSONField(default=dict),
        ),
    ]
