# Generated by Django 5.2.1 on 2025-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('vender', 'Vender'), ('admin', 'Admin'), ('editor', 'Editor'), ('verifier', 'Verifier'), ('manager', 'Manager'), ('support', 'Support'), ('auditor', 'Auditor'), ('analyst', 'Analyst'), ('moderator', 'Moderator'), ('guest', 'Guest')], default='user', max_length=50)),
                ('password', models.CharField(max_length=138)),
            ],
        ),
    ]
