# Generated by Django 5.2.1 on 2025-06-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
    ]
