# Generated by Django 5.2.1 on 2025-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0002_remove_adminuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='password',
            new_name='password_field',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('vender', 'Vender'), ('admin', 'Admin'), ('editor', 'Editor'), ('verifier', 'Verifier'), ('manager', 'Manager'), ('support', 'Support'), ('auditor', 'Auditor'), ('analyst', 'Analyst'), ('moderator', 'Moderator'), ('guest', 'Guest')], default='user', max_length=50),
        ),
    ]
