# Generated by Django 5.2.1 on 2025-05-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('download_link', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
            ],
        ),
    ]
