# Generated by Django 5.2.1 on 2025-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='video',
            field=models.CharField(),
        ),
    ]
