# Generated by Django 5.2.1 on 2025-05-21 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=200)),
                ('lng', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
                ('label', models.CharField(choices=[('home', 'HOME'), ('work', 'WORK'), ('school', 'SCHOOL'), ('other', 'OTHER')], max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('building_name', models.CharField(max_length=200)),
                ('receiver_name', models.CharField(max_length=200)),
                ('conatact', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.customuser')),
            ],
        ),
    ]
