# Generated by Django 5.2.1 on 2025-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='conatact',
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_conatact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
