# Generated by Django 5.2.1 on 2025-05-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_remove_address_conatact_address_receiver_conatact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='receiver_conatact',
            new_name='receiver_contact',
        ),
    ]
