# Generated by Django 5.2.1 on 2025-05-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_rename_receiver_conatact_address_receiver_contact'),
        ('user', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='token',
            field=models.CharField(default='EWRYU', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.customuser'),
        ),
    ]
