# Generated by Django 5.2.1 on 2025-05-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_token_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='token',
        ),
    ]
