# Generated by Django 5.2.1 on 2025-05-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('provider', 'Service Provider'), ('admin', 'Admin')], default='user', max_length=50),
        ),
    ]
