# Generated by Django 5.2.1 on 2025-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='provider_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='sum', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='provider_id',
            field=models.CharField(default='234', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-16T12:47:57.598783Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-16T12:47:57.598783Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service_name',
            field=models.CharField(default='kav', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
