# Generated by Django 5.2.1 on 2025-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_ordered_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(default='ryuio', max_length=200),
            preserve_default=False,
        ),
    ]
