# Generated by Django 5.2.1 on 2025-05-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='provider_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='provider_id',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.CharField(default='some'),
            preserve_default=False,
        ),
    ]
